version: 0.1
keywords: "ROS, Robotic, ITECH, ICD, ITKE"
title: "Task IO"
description: "Task runner for ROS based on RosBridge Package"
url: "http://behrooz-tahanzadeh.github.io/task_io/"
date: "Jan 2017"
